conda-forge/conda-build-feedstock

recipe/bld.bat, recipe/build.sh, recipe/meta.yaml, recipe/test_bdist_conda_setup.py
We were not installing or testing for `bdist_conda` previously. This adds an explicit installation step for `bdist_conda` on Unix and Windows. Also adds a simple test to verify that `bdist_conda` works ok.
Note: Based off of PR ( https://github.com/conda-forge/conda-build-feedstock/pull/9 ) to handle the checksum change.
=> Install and test for bdist_conda

recipe/meta.yaml
Appears the checksum for `conda-build`'s 2.1.1 release has changed. Not entirely sure why this is, but it is possible GitHub has changed something about how they generate archives behind the scenes. As a result, we find ourselves having to correct the checksum.
=> Fix the checksum :/

recipe/meta.yaml
This explicitly adds all of @conda-forge/core as maintainers of `conda-build`. As this is our `conda-build` package and determines, which version we are using as latest. It is paramount that all of core explicitly has access should they need it. This provides that access.
=> Add core as maintainers [ci skip]

recipe/meta.yaml
Need the update to 2.1.6 to build pyslet (https://github.com/conda-forge/staged-recipes/pull/2534) on windows/py27. Otherwise the build fails with unicode issues due to non ascii filenames in the. tar.gz
Also made use of variables as in example and added licence infos
=> Update to 2.1.6

appveyor.yml, ci_support/run_docker_build.sh, recipe/bld.bat, recipe/build.sh, recipe/meta.yaml
```
2016-08-02 1.21.10:
-------------------
Bug fixes:
----------
* Compile files ending with .py, not py.  #1163
* Move root logger to entry points, to not interfere with conda #1164 #1166
* Use setuptools entry points, rather than pre-defined scripts #1165
* Always use the long build prefix to avoid confusion #1168
Contributors:
-------------
* @mingwandroid
* @msarahan
```
=> Release 2.1.10

recipe/meta.yaml
```rst
2017-05-18 2.1.15:
Bug fixes:
----------
* Fix windows entry point exe's for spaces in the final exe path  #2039
Contributors:
-------------
* @mingwandroid
2017-05-17 2.1.14:
Enhancements:
-------------
* Add new entry point EXE's for windows that support unicode  #2031, #2033
Contributors:
-------------
* @mingwandroid
2017-05-10 2.1.13:
Bug fixes:
----------
* fix missing argument to get_site_packages function; add test coverage  #2009
* pin codecov on appveyor to 2.0.5 for now  #2009
* fix lock removal (just don't create locks for temporary directories)  #2009
Contributors:
-------------
* @msarahan
2017-05-09 2.1.12:
Bug fixes:
----------
* Clean up lock files for temporary directories also
Contributors:
-------------
* @msarahan
2017-05-09 2.1.11:
Enhancements:
------------- …
```
=> Release 2.1.15

recipe/meta.yaml
Have noticed some logging messages coming through during various build operations with `conda-build`. Suspect this was a consequence of the old `conda` 4.3.21 build, which hadn't updated the build scripts. Now that `conda` has been rebuilt correctly, it seems worthwhile to try just rebuilding `conda-build` to see if this issue goes away.
=> Rebuild in presence of the new `conda` package

README.md, recipe/meta.yaml
```
2017-09-12 2.1.18:
------------------
Bug fixes:
----------
* add SSL_CERT_FILE and REQUESTS_CA_BUNDLE to build env pass-through variables
* allow blank values for certain keys in cran-skeleton  #2153
* Ignore feature records in index for ``conda inspect``  #2253
* backport relax entry_points syntax from #1894  #2348
* delete "cc" (conda config instance) only after all usage  #2365
* backport "only set env vars in build scripts that actually have values" from #2259; #2528
Contributors:
-------------
* @aburgm
* @jakirkham
* @jjhelmus
* @kalefranz
* @nehaljwani
```
=> Release 2.1.18

recipe/build.sh, recipe/meta.yaml
bump to 3.12.0.  The moves conda-verify to run_constrained instead of just run.
This should also make this repo mergeable with defaults in the future.
=> 3.12.0; sync with defaults

.azure-pipelines/build_steps.sh, recipe/meta.yaml
Updates conda-build's requirements based on [it's included `meta.yaml`]( https://github.com/conda/conda-build/blob/3.18.6/conda.recipe/meta.yaml ).
Checklist
=> Refresh requirements

recipe/meta.yaml
Removes the warning during build:
"WARNING: Detecting which files contain PREFIX is slow, installing ripgrep makes it faster."
" 'conda install ripgrep'"
closes https://github.com/conda-forge/conda-build-feedstock/issues/102
Checklist
=> Add ripgrep to run requirements on x86_64 (linux64, osx, win64)

recipe/gh3606.patch, recipe/meta.yaml
This interferes with conda-smithy rerendering and also on linux clang compilers
Checklist
=> Remove hard-coded default path for CONDA_BUILD_SYSROOT

recipe/gh-4335-conda-411-auxlib.patch, recipe/meta.yaml
Checklist
`conda-build` imports a "non-public" function from `conda`'s `auxlib` and the location of the latter has changed with `conda=4.11.0`. See https://github.com/conda/conda-build/pull/4335 and linked issues for details.
Patch is not yet merged upstream (conda-build's CI queue is a bit long currently..)
=> Add gh-4335-conda-411-auxlib.patch

recipe/meta.yaml
Checklist
Xref: conda/conda-build#4495
In addressing the flakiness of conda-build's patch tests we found that the default `patch` shipped on MacOS (2.5.8) is insufficient (need >=2.6).
=> Add `patch` and `cctools` dependency

recipe/meta.yaml
Encountered in a local render after #181 / #182: 
```
[...]
File "C:\Users\[...]\.conda\envs\builder\lib\site-packages\conda_build\metadata.py", line 1546, in _get_contents
from conda_build.jinja_context import context_processor, UndefinedNeverFail, FilteredLoader
File "C:\Users\[...]\.conda\envs\builder\lib\site-packages\conda_build\jinja_context.py", line 13, in <module>
import toml
ModuleNotFoundError: No module named 'toml'
```
=> fix missing dependency

recipe/meta.yaml
Typically we "fix" the feedstock so as to avoid accidentally creating a new release.
Just wanted to make sure this got in
xref:
* https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/387
* https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3973
Checklist
=> Set upper bound on setuptools

recipe/meta.yaml, recipe/patches/gh4867.patch
=> Add gh4867.patch

recipe/meta.yaml
Checklist
Since the build for #225 failed (see https://github.com/conda-forge/conda-build-feedstock/runs/24916644440) I did not bump the build number.
=> Fix sha256 for 24.5.0

.azure-pipelines/azure-pipelines-win.yml, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, recipe/meta.yaml
Checklist
They are not compatible:
```
Traceback (most recent call last):
File "/home/ubuntu/.pixi/envs/conda-build/bin/conda-build", line 7, in <module>
from conda_build.cli.main_build import execute
File "/home/ubuntu/.pixi/envs/conda-build/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 19, in <module>
from .. import api, build, source, utils
File "/home/ubuntu/.pixi/envs/conda-build/lib/python3.12/site-packages/conda_build/build.py", line 54, in <module>
from .post import (
File "/home/ubuntu/.pixi/envs/conda-build/lib/python3.12/site-packages/conda_build/post.py", line 47, in <module>
from .inspect_pkg import which_package
File "/home/ubuntu/.pixi/envs/conda-build/lib/python3.12/site-packages/conda_build/inspect_pkg.py", line 28, in <module>
from .os_utils.liefldd …
```
=> Pin py-lief<0.15

recipe/meta.yaml
Due to https://github.com/conda/conda-build/issues/5594
=> avoid lief 0.16 for now

recipe/meta.yaml
take #239 a step further (matches latest repodata patch https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/947)
conda-build 25.1.1 is not yet compatible with lief 0.15, at least on mac https://github.com/conda/conda-build/issues/5594
=> restrict py-lief to <0.15

recipe/meta.yaml
issue https://github.com/conda/conda-build/issues/5594 was fixed upstream
Checklist
=> remove py-lief bound
