conda-forge/conda-build-feedstock

recipe/meta.yaml
=> Relax conda requirement to allow for conda 4.3

.travis.yml, LICENSE, appveyor.yml, ci_support/fast_finish_ci_pr_build.sh, ci_support/run_docker_build.sh, circle.yml, recipe/meta.yaml
Re-rendered with `conda-smithy` 2.1.0 and enabled Python 3.6 support.
=> Re-render 2.1.0 and add Python 3.6

appveyor.yml, recipe/meta.yaml
```
2017-03-24 2.1.8:
Enhancements:
-------------
* use symlinks when copying files from files sources to improve performance  #1867
Bug fixes:
----------
* reset build folder for each built package (fixes building multiple recipes in one command)  #1842
* wrap copy of test/source_files so that errors don't prevent a successful build  #1843
* Restore permissions when extracting from zipfiles  #1855
* pass through several Windows-specific environment variables  #1859, #1862
* python 2 os.environ string type compatibility fix  #1861
* fix indentation breaking perl package testing  #1872
* reduce scope of git try/except block so that GIT_FULL_HASH is available even if tags are not.  #1873
* fix license family comparison, especially for public-domain  #1875
* Remove python header being added …
```
=> Release 2.1.8

recipe/meta.yaml
```
2017-04-04 2.1.9:
Enhancements:
-------------
* calculate checksum and simplify cran skeleton  #1879
* backport usage of symlinks for speed from master branch  #1881
Bug fixes:
----------
* fix import tests not being run, test this functionality  #1897
Contributors:
-------------
* @isuruf
* @jjhelmus
* @johanneskoester
* @msarahan
```
=> Release 2.1.9

recipe/meta.yaml
Bug fixes:
----------
* Fix disable_pip removing packages even when they are explicit dependencies  #2129
* Remove any pyc files for entry point scripts that pip may have created #2134
* Ignore unserializable data when reading setup.py data  #2141
Contributors:
-------------
* @mandeep
* @msarahan
=> update to 2.1.17

appveyor.yml, recipe/meta.yaml
=> Update to 3.4.1

recipe/meta.yaml
=> Add glob2 condition

recipe/meta.yaml
=> revert from git_url to tarball; add CJ-Wright as maintainer

recipe/meta.yaml
=> Add python-libarchive-c dependency

recipe/meta.yaml
=> Add m2-patch as a dependency

recipe/gh3925.patch, recipe/meta.yaml
Checklist
Since https://github.com/conda-forge/conda-build-feedstock/pull/134 is stalled
cc @mbargull
=> Add gh3925 patch until 3.19.3 is merged

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_python3.6.____cpython.yaml, .ci_support/linux_64_python3.7.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_aarch64_python3.6.____cpython.yaml, .ci_support/linux_aarch64_python3.7.____cpython.yaml, .ci_support/linux_aarch64_python3.8.____cpython.yaml, .ci_support/linux_ppc64le_python3.6.____cpython.yaml, .ci_support/linux_ppc64le_python3.7.____cpython.yaml, .ci_support/linux_ppc64le_python3.8.____cpython.yaml, .ci_support/osx_64_python3.6.____cpython.yaml, .ci_support/osx_64_python3.7.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/win_64_python3.6.____cpython.yaml, .ci_support/win_64_python3.7.____cpython.yaml, .ci_support/win_64_python3.8.____cpython.yaml, LICENSE.txt, README.md, azure-pipelines.yml
Closes https://github.com/conda-forge/conda-build-feedstock/issues/142
Checklist
=> MNT: Re-rendered

recipe/meta.yaml
=> [skip ci] [ci skip] **NO_CI** add isuruf to maintainers

recipe/gh4287.patch, recipe/meta.yaml
=> Apply security patch from gh 4287

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.7.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/linux_aarch64_python3.10.____cpython.yaml, .ci_support/linux_aarch64_python3.7.____cpython.yaml, .ci_support/linux_aarch64_python3.8.____cpython.yaml, .ci_support/linux_aarch64_python3.9.____cpython.yaml, .ci_support/linux_ppc64le_python3.10.____cpython.yaml, .ci_support/linux_ppc64le_python3.7.____cpython.yaml, .ci_support/linux_ppc64le_python3.8.____cpython.yaml, .ci_support/linux_ppc64le_python3.9.____cpython.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, recipe/bld.bat, recipe/build.sh, recipe/meta.yaml
=> Update to 3.21.8

recipe/meta.yaml
=> Fix failing build on main

recipe/meta.yaml
=> Bump version to 3.23.0

recipe/meta.yaml
Checklist
Xref https://github.com/conda/conda-build/issues/4617
Corrects `zstd_compression_level` issue: https://github.com/conda/conda-build/pull/4650
=> Update to 3.23.2

recipe/0001-Fix-Remove-invalid-memoization-for-MetaData.patch, recipe/meta.yaml
Checklist
This adds the crucial bit of https://github.com/conda/conda-build/pull/4665 as a patch until a new version with the changes from that PR is released.
=> Fix: Remove invalid memoization for MetaData

.azure-pipelines/azure-pipelines-win.yml, .github/CODEOWNERS, .scripts/build_steps.sh, .scripts/run_osx_build.sh, README.md, conda-forge.yml, recipe/meta.yaml
Checklist
Supersedes #196 
CC @jezdez 
Added myself as a maintainer
=> Bump version to 3.24.0 with updated dependencies

recipe/bld.bat, recipe/build.sh, recipe/meta.yaml
=> Bump version to 3.25.0

recipe/meta.yaml
Address https://github.com/conda/conda-build/issues/4881 (well, at least work around it)
=> add cap on patchelf

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_python3.13.____cp313.yaml, .ci_support/linux_aarch64_python3.13.____cp313.yaml, .ci_support/linux_ppc64le_python3.13.____cp313.yaml, .ci_support/migrations/python313.yaml, .ci_support/osx_64_python3.13.____cp313.yaml, .ci_support/osx_arm64_python3.13.____cp313.yaml, .ci_support/win_64_python3.13.____cp313.yaml, README.md, conda-forge.yml, recipe/meta.yaml
Without a more focussed skip than #246
=> Rebuild for python 3.13 (redux)
